### ISSUE TITLE
Comparing ag-grid fails due to hidden page panel

### ISSUE THREAD

**Issue by oliverbrace** [kpmck/cypress-ag-grid#13]
Hi

Trying to use the comparison tool and I can see that it correctly compares the ag-grid (and passes) however it then tries to click on .ag-icon-next which then causes it to fail.
The page panel is hidden. The error doesn't seem to occur when the page panel is visable.

![image](https://user-images.githubusercontent.com/42202976/166895255-257ec92f-8120-43fa-8ff1-9cc35976bd4d.png)

**Comment by kpmck** [comment]
Hi @oliverbrace,
A couple questions:
1. Are you validating a paginated table? 
2. Is it expected that the `.ag-icon-next` exists on your current page? Can you verify that it actually does if so? 
3. Can you provide me with an example of your test code (method called, example of expected and actual data)?

**Comment by kpmck** [comment]
Hi @oliverbrace, I am going to close this out for now, but please let me know if you're still experiencing this and need additional assistance!
