### ISSUE TITLE
Types for `getAgGridData`

### ISSUE THREAD

**Issue by allforabit** [kpmck/cypress-ag-grid#22]
I wonder should the types for `getAgGridData` be different? It's specifying that the return type of the promise is a query object whereas it will actually be the grid data (an array of objects of each row). 

I can put together a PR for this if it seems like the correct approach.

**Comment by kpmck** [comment]
Hey there @allforabit - This is a good call out, and I appreciate you bringing it up! 

The return type of a query object was from my original plan to return objects for each cell vs just the data content (a feature that will be available on v2 coming soon). 

You're right that the return type of the `getAgGridData` should be changed to something else; possibly ` Chainable<Array<Record<string, string>>>`. This will also be updated with the new command `getAgGridElements` in v2.

**Comment by kpmck** [comment]
This was merged in with PR #31
