### ISSUE TITLE
agGridColumnFilterTextMenu does not work in ag-grid community

### ISSUE THREAD

**Issue by air2** [kpmck/cypress-ag-grid#3]
The ag-grid community edition does not have a tabbed column menu (only the filter part is shown) Therefor the test will hang on .find('ag-tab') which will never be resolved since it is not there.

````
function getMenuTabElement(agGridElement, tab) {
  return cy
    .get(agGridElement)
    .find(".ag-tab")
    .find(`.ag-icon-${tab}`)
    .filter(":visible");
}
````
This is found in the above code. So for the community edition there are no tabs. And the test fails always.

**Comment by kpmck** [comment]
Resolved with PR #4 - thank you for contributing!
