### ISSUE TITLE
MultiFilter issue

### ISSUE THREAD

**Issue by gdeo** [kpmck/cypress-ag-grid#35]
On trying to test multi-filter with checkboxes, selectAllLocaleText is ignored, and the test keeps looking for the text 'Select All'. 
```
cy.get("#myAgGrid").agGridColumnFilterCheckboxMenu({
      searchCriteria: 
      [
        {
          columnName: "Col1",
          filterValue: "option1"
          
          },
          {
            columnName: "Col1",
            filterValue: "option2",
            },
          ],
          selectAllLocaleText:"custom text",
          hasApplyButton: false
    })
```

The above has failed with the error - 
`Timed out retrying after 30000ms: Expected to find content: 'Select All' within the element:`

**Comment by kpmck** [comment]
Thanks for filing! This should be resolved with https://github.com/kpmck/cypress-ag-grid/pull/36
