### ISSUE TITLE
Filter condition 'Blank' and 'Not blank' does not work

### ISSUE THREAD

**Issue by gdeo** [kpmck/cypress-ag-grid#37]
Thank you for this awesome plugin! Has made my life so easy! Filtering ag-grid table columns has been a breeze. 

When trying to filter blanks and non-blanks, where a filterValue (text to search) is not needed, the agGridColumnFilterTextMenu or agGridColumnFilterTextFloating do not work as it keeps looking for a textbox to enter text in. Is there a workaround for this? Or am I missing something? It would be great if you could add this option to the filter functions.

**Comment by kpmck** [comment]
Hey there! I’m glad you’re getting good use of the plug-in! 😊 Would you happen to have an example grid you could share where you are seeing an issue? Or if you’re able to provide a screenshot with the HTML of the filter, that would help me find a solution for you.

**Comment by gdeo** [comment]
Attaching screenshots of the filter conditions 'Contains' and 'Blank'. As you can see, for Contains we need to enter the filterValue text, which works fine. However for Blank, we do not need to enter any text but since the code (src/agGrid/agGridInteractions.js:264:1) has the condition to verify that the filter input is visible, the test keeps searching for a text box to enter the filter value.
![8DAD3628-FA4B-4498-9C29-444E0459F2D0_4_5005_c](https://user-images.githubusercontent.com/14810456/219213777-a730ea07-1577-4af3-a6d1-123429261120.jpeg)
![72E1B20D-1934-4131-BF41-F03327DEB068_4_5005_c](https://user-images.githubusercontent.com/14810456/219213795-ce025131-74dc-42a2-9fa7-ccab82f08aa7.jpeg)

**Comment by kpmck** [comment]
This functionality is now updated with PR #40 . Please see this test for an example: https://github.com/kpmck/cypress-ag-grid/blob/master/cypress/e2e/ag-grid-data.cy.js#L437
