### ISSUE TITLE
Operator does not work on filtering

### ISSUE THREAD

**Issue by JewlsIOB** [kpmck/cypress-ag-grid#46]
I have not been able to get any but the default "operator" to work on `agGridColumnFilterTextMenu`.  When I look at the code, it seems to ignore `operator`?

https://github.com/kpmck/cypress-ag-grid/blob/master/src/agGrid/agGridInteractions.js#L335-L356

**Comment by kpmck** [comment]
Hey there, 

[This test](https://github.com/kpmck/cypress-ag-grid/blob/master/cypress/e2e/ag-grid-data.cy.js#L143-L163) uses the `agGridColumnFilterTextMenu` successfully and allows for passing in different operators. Can you please provide me with an example of how you are using this and if the grid you have implemented is similar to the sample grid used in the tests?

**Comment by JewlsIOB** [comment]
@kpmck what version of AgGrid is this currently working against?  I am wondering if since I am on v. 28 if I am just missing some of the updated functionality.  From https://www.ag-grid.com/vue-data-grid/filter-number/: 

> Note that in AG Grid versions prior to 29.2, only two Filter Conditions were supported. These appeared in the Combined Model as properties condition1 and condition2. The grid will still accept and supply models using these properties, but this behaviour is deprecated. The conditions property should be used instead.

**Comment by rakesh-rk91** [comment]
@JewlsIOB is right. The   options.searchCriteria.operator = searchCriteria.operator; should be added to the function populateSearchCriteria. Can someone please help to get this fixed ?

**Comment by kpmck** [comment]
@rakesh-rk91 @JewlsIOB I won't be able to look into placing a fix myself until later this week. If either of you are able to raise a PR with a test associated with it, I'd be happy to get it merged in ASAP!

**Comment by kpmck** [comment]
@rakesh-rk91 @JewlsIOB thanks so much for your patience, both of you. This fix has been released as part of v2.0.3. Please let me know if you see any additional issues.
