### ISSUE TITLE
Add support for ag-grid 30.2.0

### ISSUE THREAD

**Issue by air2** [kpmck/cypress-ag-grid#51]
Currently this package does not support ag-grid 30.2.0 because the grid is rendered in:
.ag-center-cols-viewport instead of .ag-center-cols-clipper

So I made a small change to make everything working again (I will open a pull request)

**Comment by kpmck** [comment]
This has been resolved by #52 -- thank you so much for contributing!

**Comment by kpmck** [comment]
This has been released as part of v.2.0.3
