### ISSUE TITLE
getAgGridData() return "" during parsing boolean value

### ISSUE THREAD

**Issue by irene604** [kpmck/cypress-ag-grid#56]
maybe because it is a nested value? but how i can deal with it

**Comment by irene604** [comment]
![image](https://github.com/kpmck/cypress-ag-grid/assets/84325188/a34c8113-1bd5-4f03-ad3a-b73f7be881e5)

**Comment by kpmck** [comment]
Can you please provide more details?

**Comment by irene604** [comment]
Hi, thanks for a quick answer. I can't share code with you, but will try to describe the problem

**Comment by kpmck** [comment]
Hi @irene604 any updates from your end?

**Comment by kpmck** [comment]
Closing as issue has gone stale. Please feel free to open a new ticket if this issue persists.
