### ISSUE TITLE
Data Mapping Issue with Pinned Columns when using Cypress-Ag-Grid

### ISSUE THREAD

**Issue by JmdAtKmd** [kpmck/cypress-ag-grid#60]
There seems to be a data mapping issue, when testing grids with pinned columns using Cypress-Ag-Grid. The data in the pinned columns does not match the expected output, as evidenced in the provided Stackblitz project.

Expected Behavior
The data in the grid should match the following expected structure:

```
const expectedData = [
    { Mission: 'Voyager', Company: 'NASA', Location: 'Cape Canaveral', Date: '1977-09-05', Price: 86580000 },
    { Mission: 'Apollo 13', Company: 'NASA', Location: 'Kennedy Space Center', Date: '1970-04-11', Price: 3750000 },
    { Mission: 'Falcon 9', Company: 'SpaceX', Location: 'Cape Canaveral', Date: '2015-12-22', Price: 9750000 },
];
```

Actual Behavior
The actual data extracted from the grid during testing does not align with the expected results:

```
const actualData = [
    { Mission: '', Company: 'Titan-Centaur', Location: 'Voyager', Date: 'NASA', Successful: 'Cape Canaveral', Rocket: '1977-09-05' },
    { Mission: '', Company: 'Saturn V', Location: 'Apollo 13', Date: 'NASA', Successful: 'Kennedy Space Center', Rocket: '1970-04-11' },
    { Mission: '', Company: 'Falcon 9', Location: 'Falcon 9', Date: 'SpaceX', Successful: 'Cape Canaveral', Rocket: '2015-12-22' },
];
```

Steps to Reproduce
Access the Stackblitz project
Run the Cypress tests included in the project.
Observe the discrepancy between the expected and actual data in the test results.

StackBlitz:
https://stackblitz.com/~/github.com/JmdAtKmd/cypress-ag-grid-pinned-bug

Repository:
https://github.com/JmdAtKmd/cypress-ag-grid-pinned-bug

Expected Outcome
A resolution to ensure accurate data mapping in Ag Grid when tested with Cypress-Ag-Grid, particularly for scenarios involving pinned columns.

Also it seems that this PR fixes the issue: https://github.com/kpmck/cypress-ag-grid/pull/43

**Comment by tgdevereux** [comment]
fyi, my team is also hitting this issue when running cypress tests against grids with pinned columns.It looks like it only repro's when we update to cypress-ag-grid to v3, but that version is required to support ag-grid v31.

Until a fix, such as https://github.com/kpmck/cypress-ag-grid/pull/43, is published, is there a workaround to this issue?

**Comment by kpmck** [comment]
Hey @tgdevereux and @JmdAtKmd - thank you for bringing this to my attention. I am looking at this right away.

**Comment by kpmck** [comment]
This should be fixed with the latest fixes and #43 merged in. Please use version 3.2.0.

**Comment by finixfx** [comment]
What is the problem? Is it something that my changes introduced? I can try to fix the problem if you describe what is not working :)

**Comment by kpmck** [comment]
Hey @finixfx thank you for your patience! This has been republished as 3.2.1. Please let me know if you see any issues on your side, and thank you again for raising this bug!

**Comment by JmdAtKmd** [comment]
Awesome, thanks for the quick fix @kpmck and the awesome package, really makes testing the grid a breeze!
