### ISSUE TITLE
Getting -SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'     at EventEmitter.handler    after adding import "cypress-ag-grid"; to the Index.js file

### ISSUE THREAD

**Issue by MonikaJaiswalMJ** [kpmck/cypress-ag-grid#9]

**Comment by MonikaJaiswalMJ** [comment]
@kpmck  Can you please help me in this

**Comment by kpmck** [comment]
Hi @MonikaJaiswalMJ . This type of error typically stems from configuration in your project, rather than from the plugin. Without having details on how your Cypress project is configured, it would be difficult for me to help resolve this issue for you. However, here is a relevant StackOverflow answer that may help! https://stackoverflow.com/questions/53650208/cypress-parseerror-import-and-export-may-appear-only-with-sourcetype-modu

**Comment by MonikaJaiswalMJ** [comment]
@kpmck Actually this specific error I am getting after adding the Import statement only, once I have removed this, my tests are working fine

**Comment by MonikaJaiswalMJ** [comment]
@kpmck 
// ***********************************************************
// This example support/index.js is processed and
// loaded automatically before your test files.
//
// This is a great place to put global configuration and
// behavior that modifies Cypress.
//
// You can change the location of this file or turn off
// automatically serving support files with the
// 'supportFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/configuration
// ***********************************************************

// Import commands.js using ES2015 syntax:
import './commands'
import 'cypress-ag-grid'
// Alternatively you can use CommonJS syntax:
// require('./commands')

**Comment by kpmck** [comment]
Would you be able to provide a reproducible solution? Are you using TypeScript elsewhere in your project, or is this pure JavaScript?

**Comment by MonikaJaiswalMJ** [comment]
@kpmck Issue has been resolved, Thank You :)

**Comment by kpmck** [comment]
I’m glad to hear that! Would you mind sharing the resolution in case anyone else incurs this issue?

**Comment by MonikaJaiswalMJ** [comment]
@kpmck  Actually Cucumber plugin was causing that issue, I have just removed the Cucumber plugin and issue got resolved

**Comment by shalini1691** [comment]
Hi @kpmck , I am facing a similar issue in my project, but as many teams are using the same component, I cannot remove the cucumber plugin. Any workaround for this issue other than removing the cucumber plugin ?

**Comment by kpmck** [comment]
> Would you be able to provide a reproducible solution? Are you using TypeScript elsewhere in your project, or is this pure JavaScript?

@shalini1691 would you mind answering the above questions please?

**Comment by shalini1691** [comment]
We are not using TypeScript @kpmck . Its pure Javascript.

**Comment by shalini1691** [comment]
Sure @kpmck , 
1) You have to do npm install cypress-cucumber-preprocessor
2) Add the below code in Plugin>index.js 
   /**
 * @type {Cypress.PluginConfig}
 */
// eslint-disable-next-line no-unused-vars
const cucumber = require('cypress-cucumber-preprocessor').default
module.exports = (on, config) => {
on('file:preprocessor', cucumber());
}
3) Do a npm run test - check if you are able to see the issue. 
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' at EventEmitter.handler after adding import "cypress-ag-grid"; to the Index.js file

**Comment by kpmck** [comment]
@shalini1691 I have followed your instructions, but I am not able to reproduce your issue. If you are able to upload a reproducible solution to GitHub that I can pull down, that would be helpful.

**Comment by kpmck** [comment]
Hi @shalini1691, just wanted to follow up on if you were able to resolve your issue or create a reproducible solution?

**Comment by shalini1691** [comment]
Hi @kpmck , I still couldn't figure out a solution for this, I will do a detailed analysis on this and let you know the outcome.

**Comment by Pallabee94** [comment]
I am facing the same issue as well, and I cannot remove Cucumber plugin as it is used in our project. Please let me know if there is any workaround for this. @kpmck @shalini1691

**Comment by kpmck** [comment]
Hello @Pallabee94 , unfortunately I have not been able to reproduce this in my solutions that leverage cypress-cucumber-preprocessor, and won't be able to resolve without a reproducible solution.

**Comment by erpachecomo** [comment]
So this plugin needs webpack as the file preprocessor, and that's the reason when we try to use other preprocessors plugins. 
There is a current thread on cypress: https://github.com/cypress-io/cypress/issues/5832.

**Comment by Beginner-ft** [comment]
Hi I am facing the same issue. I cannot remove the cucumber-preprocessor plugin as we follow the bdd structure. So has anyone found a workaround for this issue @shalini1691 @kpmck

**Comment by kpmck** [comment]
@Beginner-ft @shalini1691 if anyone is able to provide a minimally reproducible repo, I can work in a solution.

**Comment by Beginner-ft** [comment]
@kpmck  Sorry i'm unable share it. But we use typescript and cucumber preprocessor along with browserify preprocessor

**Comment by kpmck** [comment]
@Beginner-ft hey there, are you able to create a small repository with those conditions that can be used for testing/debugging?

**Comment by Beginner-ft** [comment]
Since i'm new to cypress it would be a time taking process for me to reproduce it and i needed a quicker solution aswsuming someone had already resolved it @kpmck
